### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'features')

### ISSUE THREAD

**Issue by perkinsjr** [clerkinc/use-stripe-subscription#2]
## Description 

After playing around with this package. I created two products with two prices and zero features. I cannot load the project due to an error. 

```bash
error - TypeError: Cannot read properties of undefined (reading 'features')
    at file:///Users/jamesperkins/Development/stripe-no-webhooks/node_modules/use-stripe-subscription/dist/use-stripe-subscription.modern.js:1:1115
```
It seems this line causes the issue:

```javascript
 const products = new Array(
    configurations.data[0].features.subscription_update.products.length
  );
```

minimal repro based upon the original demo 

https://github.com/perkinsjr/stripe-no-webhooks

**Comment by colinclerk** [comment]
This might be because you haven't set your billing portal "configuration":

> After Products and Prices are configured, developers should configure their [Customer portal settings](https://dashboard.stripe.com/test/settings/billing/portal). The settings here are how use-stripe-subscription determines which Products and Prices users can purchase in a self-serve manner. For security reasons, useSubscription() only returns products that are listed in the "Products" section of this page.

If this turns out to be it, let us know how we can document it better!

**Comment by perkinsjr** [comment]
Yup missed the "Products" section in my own customer portal in test mode. I will work on improving the Readme this week.
